name: 'Antrea test'
# If any file change in the antrea path a new build will be triggered
on:
  push:
    branches: [ main ]
    paths:
      - antrea/**

jobs:
  antrea-job:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Run
      working-directory: ./antrea
      run: ./setup.sh
