name: 'Flannel test'
# If any file change in the flannel path a new build will be triggered
on:
  push:
    branches: [ main ]
    paths:
      - flannel/**

jobs:
  flannel-job:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Run
      working-directory: ./flannel
      run: ./setup.sh
